### ISSUE TITLE
Normalize OS names in results (trailing newlines, capitalization)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-analysis#17]
Filing an issue here for lack of an obvious place. In https://github.com/foolip/ecosystem-infra-stats/pull/10#discussion_r180869876 I account for 'linux\n' being the platform for some runs in https://wpt.fyi/api/runs?max-count=1000.

This is presumably because it's like that in the input. When merging the split files into single files, some normalization of this and macos vs. macOS might be good.

**Comment by lukebjerring** [comment]
Unrelated: Pretty sure max-count caps out @ 500 ([code](https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/params.go#L23))

Related: That (`linux\n`) would be from a manual entry and the data source should be corrected.
