### ISSUE TITLE
Set up a regular compute + upload run

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/results-analysis#26]
We need to be regularly running the interop (metrics) computation.

**Comment by mdittmer** [comment]
@lukebjerring do you think the initial implementation of this should use the current (non hash-aligned) behaviour that trusts the identity of the four "latest runs" from the endpoint?

**Comment by mdittmer** [comment]
i.e., determine which runs to compare using [`FetchLatestRuns`](https://github.com/web-platform-tests/wpt.fyi/blob/df6a14d0dc76b2f706d1a69c8de4fded9e74d32b/shared/fetch_runs.go#L21)

**Comment by lukebjerring** [comment]
Yes; we can follow up later with a `?complete=true` patch to the `/api/runs` fetch, and check whether we already have uploaded results for that sha.

This issue simply covers regular (daily, for now) running of the tool.
