### ISSUE TITLE
Migrate old project:metrics issues to this repo

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-analysis#28]
https://github.com/web-platform-tests/results-collection/issues?q=is%3Aopen+is%3Aissue+label%3Aproject%3Ametrics

Given how few there are, doing it manually would be fine. Some might be obsolete anyway.

**Comment by mdittmer** [comment]
Migrated all but one. Waiting on @lukebjerring's word on whether it is still relevant.

**Comment by foolip** [comment]
Original link now has no results, so assuming it was resolved. Thanks @mdittmer!
