### ISSUE TITLE
Brower/OS version and other info not included in merged report.json?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-analysis#37]
Playing with the wptd-results bucket, it looks like browser and OS version isn't inclcuded in the report.json but is only part of the directory name. Timestamps from datastore should probably also be part of the report.json somewhat.

@mdittmer @Hexcles, is the plan to put these JSON files into the same bucket as the receiver writes to, or submit the to the receiver one by one and get to the final state that way?

P.S. I'm operating under the assumption that everything about the run should be possible to derive from the final JSON files, so that datastore contains only redundant information. This is because it's easy to copy the whole bucket, but there's no way to dump the datastore information currently. And having all of the data for external ad-hoc analysis or forking wpt.fyi is important.

**Comment by Hexcles** [comment]
Moved to a new repo.
