### ISSUE TITLE
Port compute sub-package

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/results-analysis#4]
https://github.com/web-platform-tests/results-collection/tree/master/metrics/compute

**Comment by foolip** [comment]
OK, so from https://github.com/orgs/web-platform-tests/projects/1 I have learned that projects are more like issues and PRs that repositories. They can't be deleted, only closed.

(Wanted to see how they work, if we can use them either to mirror our OKRs, or perhaps more usefully for work that crosses repos. Or not, organizing task lists is more seductive then useful, it seems.)

**Comment by foolip** [comment]
Actually, no, they can also be deleted, I just did :)

**Comment by mdittmer** [comment]
Yeah. AFAICT projects are bound to repositories, so they're not so good for cross-cutting task lists.

**Comment by mdittmer** [comment]
... er... that's not right. You linked to an org-level (not repo-level) project. As you mentioned though, not entirely convinced the extra documenting of work is worth the effort.

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/results-analysis/pull/15
