### ISSUE TITLE
Travis CI is failing

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-analysis#61]
See failures in https://github.com/web-platform-tests/results-analysis/pull/60/checks.

**Comment by foolip** [comment]
See also https://github.com/web-platform-tests/results-analysis/runs/43012777, the build for master after that PR was merged.

**Comment by foolip** [comment]
https://travis-ci.org/web-platform-tests/results-analysis/builds shows that cron jobs on master have been failing for a very long time. Nevertheless, I'll enable them for travis-ci.com as well, just in case they have an important side effect still.

**Comment by lukebjerring** [comment]
They fail because there's no aligned experimental runs (but it tries to compute Interop for them nonetheless)

**Comment by foolip** [comment]
Are the results from this repo still what is used to serve the interop views? If so can you confirm that it's still working after the move to travis-ci.com despite the failures?

**Comment by lukebjerring** [comment]
Yes, and will do. FTR it's simply "does the default Interop query show results for within 24h?"

**Comment by lukebjerring** [comment]
Dec 16.. looks like we have a problem with the cron @mdittmer ?

**Comment by mdittmer** [comment]
AFAICT this is still failing on the already known issue: https://staging.wpt.fyi/api/runs?aligned=true&label=experimental `404`s
