### ISSUE TITLE
Merge compat-2021/interop-2022 generation code

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/results-analysis#77]
It doesn't feel like it rationally makes sense to have different scoring code, etc.; we should just have a single implementation of the scoring for interop for any year, just changing what labels get picked.

**Comment by gsnedders** [comment]
fixed in https://github.com/web-platform-tests/results-analysis/compare/interop-2023-analysis (cc @DanielRyanSmith)

**Comment by foolip** [comment]
There's now a single script and we're freezing scores at the end of each year.
